// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALWTmoZS5lXO7AiAca7BX1A4gSGKK8H-E',
    appId: '1:77106185981:web:cb06ca521b3bede3902094',
    messagingSenderId: '77106185981',
    projectId: 'theactualproject-ab1c1',
    authDomain: 'theactualproject-ab1c1.firebaseapp.com',
    storageBucket: 'theactualproject-ab1c1.appspot.com',
    measurementId: 'G-26F2H6FNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOLkmwZ_A0ICRn5XsMBD7Vp6p5peLqeo',
    appId: '1:77106185981:android:960ac6fec83dd792902094',
    messagingSenderId: '77106185981',
    projectId: 'theactualproject-ab1c1',
    storageBucket: 'theactualproject-ab1c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIHkirO-Kccjy4gu2iT7p_FQKuLe4MSs',
    appId: '1:77106185981:ios:515f828f63e71cdd902094',
    messagingSenderId: '77106185981',
    projectId: 'theactualproject-ab1c1',
    storageBucket: 'theactualproject-ab1c1.appspot.com',
    iosBundleId: 'com.example.actualprojectforril',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIHkirO-Kccjy4gu2iT7p_FQKuLe4MSs',
    appId: '1:77106185981:ios:515f828f63e71cdd902094',
    messagingSenderId: '77106185981',
    projectId: 'theactualproject-ab1c1',
    storageBucket: 'theactualproject-ab1c1.appspot.com',
    iosBundleId: 'com.example.actualprojectforril',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALWTmoZS5lXO7AiAca7BX1A4gSGKK8H-E',
    appId: '1:77106185981:web:118d24a5aeb78bef902094',
    messagingSenderId: '77106185981',
    projectId: 'theactualproject-ab1c1',
    authDomain: 'theactualproject-ab1c1.firebaseapp.com',
    storageBucket: 'theactualproject-ab1c1.appspot.com',
    measurementId: 'G-SN54575PWY',
  );
}
